// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Core__Result from "@rescript/core/src/Core__Result.mjs";

function optionNone(zora, actual, msg) {
  if (msg !== undefined) {
    zora.ok(Core__Option.isNone(actual), msg);
  } else {
    zora.ok(Core__Option.isNone(actual));
  }
}

function optionSome(zora, actual, check) {
  if (actual !== undefined) {
    return check(zora, Caml_option.valFromOption(actual));
  } else {
    zora.fail("Expected Some value, got None");
    return ;
  }
}

function resultError(zora, actual, message) {
  zora.ok(Core__Result.isError(actual), message);
}

function resultOk(zora, actual, check) {
  if (actual.TAG === "Ok") {
    return check(zora, actual._0);
  }
  zora.fail("Expected ok value, got error");
}

export {
  optionNone ,
  optionSome ,
  resultError ,
  resultOk ,
}
/* No side effect */
